import { useState } from 'react';

export default function VerificationForm({ customer }) {
    const [code, setCode] = useState(''); const [message, setMessage] = useState(''); const [error, setError] = useState(''); const [sent, setSent] = useState(false); const [file, setFile] = useState(null);
    const headers = { Accept: 'application/json', 'X-CSRF-TOKEN': document.querySelector('meta[name="csrf-token"]')?.content };
    const send = async () => { const r=await fetch(route('profile.whatsapp.send'),{method:'POST',headers}); const d=await r.json(); setSent(true); setMessage(`${d.message} Kode demo lokal: ${d.demo_code}`); };
    const verify = async () => { setError(''); const r=await fetch(route('profile.whatsapp.verify'),{method:'POST',headers:{...headers,'Content-Type':'application/json'},body:JSON.stringify({code})}); const d=await r.json(); if(!r.ok){setError(d.message);return;} setMessage(d.message); };
    const upload = async () => { if(!file)return; setError(''); const data=new FormData();data.append('ktp_file',file);const r=await fetch(route('profile.ktp.upload'),{method:'POST',headers,body:data});const d=await r.json();if(!r.ok){setError(d.errors?.ktp_file?.[0]||d.message);return;}setMessage(d.message); };
    return <div className="max-w-xl"><h3 className="text-lg font-bold text-slate-900">Verifikasi akun</h3><p className="mt-1 text-sm text-slate-500">Unggah KTP untuk mengaktifkan status VERIFIED. Verifikasi WhatsApp tetap tersedia untuk memastikan nomor kontak Anda.</p><div className="mt-6 space-y-4"><div className="rounded-xl border p-4"><div className="flex items-center justify-between gap-3"><div><b>Nomor WhatsApp</b><p className="text-sm text-slate-500">{customer.phone}</p></div>{customer.phone_verified_at?<span className="rounded-full bg-emerald-50 px-3 py-1 text-xs font-bold text-emerald-700">Terverifikasi</span>:<button onClick={send} className="rounded-lg bg-indigo-600 px-3 py-2 text-sm font-bold text-white">Kirim kode</button>}</div>{sent&&!customer.phone_verified_at&&<div className="mt-4 flex gap-2"><input value={code} onChange={e=>setCode(e.target.value)} placeholder="Kode 6 digit" className="w-full rounded-lg border-slate-200"/><button onClick={verify} className="rounded-lg border px-3 text-sm font-bold">Verifikasi</button></div>}</div><div className="rounded-xl border p-4"><div className="flex items-center justify-between"><div><b>Verifikasi KTP</b><p className="text-sm text-slate-500">{customer.ktp_verified_at?'KTP berhasil diunggah': 'Belum ada dokumen KTP'}</p></div>{customer.ktp_verified_at&&<span className="rounded-full bg-emerald-50 px-3 py-1 text-xs font-bold text-emerald-700">Terverifikasi</span>}</div>{!customer.ktp_verified_at&&<div className="mt-4 flex flex-wrap gap-2"><input type="file" accept="image/jpeg,image/png,application/pdf" onChange={e=>setFile(e.target.files?.[0])} className="text-sm"/><button onClick={upload} disabled={!file} className="rounded-lg border px-3 py-2 text-sm font-bold disabled:opacity-50">Upload KTP</button></div>}</div>{customer.status==='VERIFIED'&&<p className="rounded-lg bg-emerald-50 p-3 text-sm font-bold text-emerald-700">Akun Anda telah VERIFIED.</p>}{message&&<p className="rounded-lg bg-emerald-50 p-3 text-sm text-emerald-700">{message}</p>}{error&&<p className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}</div></div>;
}
