import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import InputError from '@/Components/InputError';
import InputLabel from '@/Components/InputLabel';
import TextInput from '@/Components/TextInput';
import { Head, useForm } from '@inertiajs/react';

export default function Form({ vehicle, categories, features, statuses }) {
 const {data,setData,post,transform,processing,errors}=useForm({vehicle_category_id:vehicle?.vehicle_category_id??'',code:vehicle?.code??'',brand:vehicle?.brand??'',model:vehicle?.model??'',variant:vehicle?.variant??'',year:vehicle?.year??new Date().getFullYear(),license_plate:vehicle?.license_plate??'',color:vehicle?.color??'',transmission:vehicle?.transmission??'AUTOMATIC',fuel_type:vehicle?.fuel_type??'GASOLINE',seat_capacity:vehicle?.seat_capacity??4,daily_price:vehicle?.daily_price??'',driver_daily_price:vehicle?.driver_daily_price??0,security_deposit:vehicle?.security_deposit??0,current_odometer:vehicle?.current_odometer??0,status:vehicle?.status??'AVAILABLE',description:vehicle?.description??'',featured:vehicle?.featured??false,feature_ids:vehicle?.features?.map(f=>f.id)??[],images:[],delete_image_ids:[],primary_image_id:vehicle?.images?.find(i=>i.is_primary)?.id??''});
 const submit=(e)=>{e.preventDefault(); if(vehicle) { transform(values=>({...values,_method:'put'})); post(route('admin.vehicles.update',vehicle.id),{forceFormData:true}); } else post(route('admin.vehicles.store'),{forceFormData:true});};
 const field=(key,label,type='text')=><div><InputLabel value={label}/><TextInput type={type} value={data[key]} className="mt-1 w-full" onChange={e=>setData(key,e.target.value)}/><InputError message={errors[key]} className="mt-1"/></div>;
 return <AuthenticatedLayout header={<h2 className="text-xl font-semibold">{vehicle?'Edit':'Tambah'} Kendaraan</h2>}><Head title="Kendaraan"/><form onSubmit={submit} className="mx-auto grid max-w-5xl grid-cols-1 gap-4 p-6 md:grid-cols-2"><div>{field('code','Kode')}</div><div>{field('brand','Merek')}</div><div>{field('model','Model')}</div><div>{field('variant','Varian')}</div><div>{field('year','Tahun','number')}</div><div>{field('license_plate','Plat nomor')}</div><div>{field('color','Warna')}</div><div>{field('seat_capacity','Kapasitas kursi','number')}</div><div>{field('daily_price','Harga harian','number')}</div><div>{field('driver_daily_price','Harga driver harian','number')}</div><div>{field('security_deposit','Deposit','number')}</div><div>{field('current_odometer','Odometer','number')}</div>
 <div><InputLabel value="Kategori"/><select className="mt-1 w-full rounded border-gray-300" value={data.vehicle_category_id} onChange={e=>setData('vehicle_category_id',e.target.value)}><option value="">Pilih kategori</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><InputError message={errors.vehicle_category_id}/></div><div><InputLabel value="Status"/><select className="mt-1 w-full rounded border-gray-300" value={data.status} onChange={e=>setData('status',e.target.value)}>{statuses.map(s=><option key={s}>{s}</option>)}</select></div>
 <div><InputLabel value="Transmisi"/><select className="mt-1 w-full rounded border-gray-300" value={data.transmission} onChange={e=>setData('transmission',e.target.value)}><option>AUTOMATIC</option><option>MANUAL</option></select></div><div><InputLabel value="Bahan bakar"/><select className="mt-1 w-full rounded border-gray-300" value={data.fuel_type} onChange={e=>setData('fuel_type',e.target.value)}><option>GASOLINE</option><option>DIESEL</option><option>ELECTRIC</option><option>HYBRID</option></select></div>
 <div className="md:col-span-2"><InputLabel value="Fitur"/><div className="mt-2 flex flex-wrap gap-4">{features.map(f=><label key={f.id}><input type="checkbox" checked={data.feature_ids.includes(f.id)} onChange={e=>setData('feature_ids',e.target.checked?[...data.feature_ids,f.id]:data.feature_ids.filter(id=>id!==f.id))}/> {f.name}</label>)}</div></div>{vehicle?.images?.length>0&&<div className="md:col-span-2"><InputLabel value="Kelola foto yang sudah diunggah"/><div className="mt-2 grid grid-cols-2 gap-4 sm:grid-cols-4">{vehicle.images.map(image=><div key={image.id} className="overflow-hidden rounded-xl border"><img src={`/storage/${image.file_path}`} className="h-28 w-full object-cover"/><div className="space-y-2 p-3 text-sm"><label className="flex items-center gap-2"><input type="radio" name="primary_image" checked={Number(data.primary_image_id)===image.id} onChange={()=>setData('primary_image_id',image.id)}/> Foto utama</label><label className="flex items-center gap-2 text-red-700"><input type="checkbox" checked={data.delete_image_ids.includes(image.id)} onChange={e=>setData('delete_image_ids',e.target.checked?[...data.delete_image_ids,image.id]:data.delete_image_ids.filter(id=>id!==image.id))}/> Hapus</label></div></div>)}</div></div>}<div className="md:col-span-2"><InputLabel value="Tambah foto baru (maks. 8)"/><input type="file" multiple accept="image/*" onChange={e=>setData('images',Array.from(e.target.files))}/><InputError message={errors.images} className="mt-1"/></div><div className="md:col-span-2"><InputLabel value="Deskripsi"/><textarea className="mt-1 w-full rounded border-gray-300" value={data.description} onChange={e=>setData('description',e.target.value)}/></div><div className="md:col-span-2"><button disabled={processing} className="rounded bg-indigo-600 px-4 py-2 text-white">Simpan kendaraan</button></div></form></AuthenticatedLayout>;
}
