import { Head, useForm, usePage } from '@inertiajs/react';
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';

const Error = ({ message }) => message ? <small className="block text-red-600">{message}</small> : null;

export default function Edit({ settings }) {
    const form = useForm({ ...settings, hero_image: null });
    const flash = usePage().props.flash;
    const field = (key, label, type = 'text') => <label>{label}<input type={type} value={form.data[key] || ''} onChange={event => form.setData(key, event.target.value)} className="mt-1 w-full rounded-xl border-slate-200" /><Error message={form.errors[key]} /></label>;

    return <AuthenticatedLayout header="Settings"><Head title="Settings" /><div className="max-w-3xl"><h1 className="text-2xl font-black">Pengaturan aplikasi</h1>{flash?.success && <p className="mt-4 rounded-xl bg-emerald-50 p-4 text-emerald-700">{flash.success}</p>}{Object.keys(form.errors).length > 0 && <p className="mt-4 rounded-xl bg-red-50 p-4 text-red-700">Periksa kembali data yang diisi.</p>}<form onSubmit={event => { event.preventDefault(); form.post(route('admin.settings.update'), { forceFormData: true }); }} className="mt-6 grid gap-5 rounded-2xl bg-white p-6 shadow sm:grid-cols-2">{field('company_name', 'Nama perusahaan')}{field('primary_color', 'Warna utama', 'color')}<label className="sm:col-span-2">Judul hero<input value={form.data.hero_title} onChange={event => form.setData('hero_title', event.target.value)} className="mt-1 w-full rounded-xl border-slate-200" /><Error message={form.errors.hero_title} /></label><label className="sm:col-span-2">Subjudul hero<input value={form.data.hero_subtitle || ''} onChange={event => form.setData('hero_subtitle', event.target.value)} className="mt-1 w-full rounded-xl border-slate-200" /></label><label className="sm:col-span-2">Gambar hero<input type="file" accept="image/*" onChange={event => form.setData('hero_image', event.target.files?.[0] || null)} className="mt-1 w-full" /><Error message={form.errors.hero_image} />{settings.hero_image && <img src={settings.hero_image} className="mt-3 h-32 rounded-xl object-cover" />}</label>{field('driver_in_city', 'Driver dalam kota / hari', 'number')}{field('driver_out_city', 'Driver luar kota / hari', 'number')}<div className="sm:col-span-2 border-t pt-5"><h2 className="font-black">Kontak & lokasi perusahaan</h2></div><label className="sm:col-span-2">Alamat<textarea value={form.data.company_address || ''} onChange={event => form.setData('company_address', event.target.value)} className="mt-1 w-full rounded-xl border-slate-200" /></label>{field('company_location', 'Lokasi / Google Maps')}{field('company_phone', 'Nomor telepon', 'tel')}{field('company_whatsapp', 'Nomor WhatsApp', 'tel')}<div className="sm:col-span-2 border-t pt-5"><h2 className="font-black">WhatsApp Gateway</h2><p className="mt-1 text-sm text-slate-500">API key dan URL gateway tetap dikelola melalui konfigurasi server.</p></div>{field('whatsapp_session_id', 'Session ID')}{field('whatsapp_admin_phone', 'Nomor WhatsApp admin', 'tel')}<div className="sm:col-span-2 border-t pt-5"><h2 className="font-black">Media sosial</h2></div>{field('social_instagram', 'Instagram (URL atau username)')}{field('social_facebook', 'Facebook (URL)')}{field('social_tiktok', 'TikTok (URL atau username)')}<button disabled={form.processing} className="sm:col-span-2 rounded-xl bg-indigo-600 py-3 font-bold text-white disabled:opacity-50">{form.processing ? 'Menyimpan...' : 'Simpan settings'}</button></form></div></AuthenticatedLayout>;
}
