import { Head } from '@inertiajs/react';
import { useState } from 'react';
import PublicLayout from '@/Layouts/PublicLayout';

export default function Register({ bookingVehicleId }) {
    const [form, setForm] = useState({ full_name: '', email: '', phone: '', address: '', password: '', password_confirmation: '', booking_vehicle_id: bookingVehicleId || '' });
    const [errors, setErrors] = useState({}); const [success, setSuccess] = useState(null); const [loading, setLoading] = useState(false);
    const submit = async (event) => { event.preventDefault(); setLoading(true); setErrors({}); const response = await fetch(route('customer-registration.store'), { method: 'POST', headers: { 'Content-Type': 'application/json', Accept: 'application/json', 'X-CSRF-TOKEN': document.querySelector('meta[name="csrf-token"]')?.content }, body: JSON.stringify(form) }); const data = await response.json(); setLoading(false); if (!response.ok) { setErrors(data.errors || {}); return; } setSuccess(data); };
    const field = (key, label, type = 'text') => <label className="block text-sm font-semibold text-slate-700">{label}{type === 'textarea' ? <textarea required value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})} rows="4" className="mt-1.5 w-full rounded-xl border-slate-200" /> : <input required type={type} value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})} className="mt-1.5 w-full rounded-xl border-slate-200" />}{errors[key] && <small className="mt-1 block text-red-600">{errors[key][0]}</small>}</label>;
    return <PublicLayout><Head title="Daftar Pelanggan" /><main className="mx-auto max-w-xl px-6 py-12"><div className="rounded-3xl bg-white p-7 shadow-sm ring-1 ring-slate-200 sm:p-10"><h1 className="text-3xl font-black">Daftar pelanggan</h1><p className="mt-2 text-slate-500">Buat akun untuk booking dan melihat riwayat perjalanan Anda.</p>{bookingVehicleId && <p className="mt-4 rounded-xl bg-blue-50 p-3 text-sm font-semibold text-blue-800">Daftar terlebih dahulu untuk melanjutkan booking mobil pilihan Anda.</p>}{success ? <div className="mt-6 rounded-2xl bg-emerald-50 p-5 text-emerald-800">{success.message}<br/>Kode pelanggan: <b>{success.customer_code}</b><a href={success.redirect} className="mt-3 block font-bold underline">Lanjut ke beranda →</a></div> : <form onSubmit={submit} className="mt-7 space-y-5">{field('full_name','Nama lengkap')}{field('email','Email untuk login','email')}{field('phone','Nomor WhatsApp','tel')}{field('address','Alamat','textarea')}{field('password','Password','password')}{field('password_confirmation','Konfirmasi password','password')}<button disabled={loading} className="w-full rounded-xl bg-blue-600 py-3.5 font-bold text-white disabled:opacity-60">{loading ? 'Mendaftarkan...' : 'Buat akun pelanggan'}</button></form>}</div></main></PublicLayout>;
}
