import {Head, useForm} from '@inertiajs/react';
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
const money = value => `Rp ${Number(value || 0).toLocaleString('id-ID')}`;
export default function Create({booking, checkout}) {
    const lateMinutes = Math.max(0, Math.ceil((Date.now() - new Date(booking.end_datetime).getTime()) / 60000));
    const lateFee = Math.ceil(Math.max(0, lateMinutes - 60) / 60) * 50000;
    const form = useForm({odometer: booking.vehicle.current_odometer, fuel_level: 100, damage_fee: 0, fuel_fee: 0, cleaning_fee: 0, notes: '', items: (checkout?.items || []).map(item => ({checklist_code: item.checklist_code, checklist_name: item.checklist_name, condition_status: 'GOOD', notes: ''}))});
    const updateItem = (index, key, value) => form.setData('items', form.data.items.map((item, itemIndex) => itemIndex === index ? {...item, [key]: value} : item));
    return <AuthenticatedLayout header="Check-in Pengembalian"><Head title="Check-in Pengembalian"/><div className="max-w-3xl"><h1 className="text-2xl font-black">Konfirmasi pengembalian</h1><p className="mt-1 text-slate-500">{booking.booking_code} · {booking.vehicle.brand} {booking.vehicle.model}</p><form onSubmit={event => {event.preventDefault(); form.post(route('admin.returns.store', booking.id));}} className="mt-6 grid gap-4 rounded-2xl bg-white p-6 shadow sm:grid-cols-2"><div className="sm:col-span-2 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900"><b>Denda keterlambatan otomatis:</b> {lateMinutes > 60 ? `${lateMinutes} menit terlambat · estimasi ${money(lateFee)}` : 'belum ada (toleransi 60 menit).'}<br/>Sistem menghitung final saat check-in disimpan: Rp50.000 per jam setelah toleransi.</div><label>Odometer akhir<input type="number" value={form.data.odometer} onChange={event => form.setData('odometer', event.target.value)} className="mt-1 w-full rounded-xl border-slate-200"/></label><label>Bahan bakar akhir (%)<input type="number" min="0" max="100" value={form.data.fuel_level} onChange={event => form.setData('fuel_level', event.target.value)} className="mt-1 w-full rounded-xl border-slate-200"/></label>{form.data.items.length > 0 && <div className="sm:col-span-2 rounded-xl border border-slate-200 p-4"><h2 className="font-black">Checklist checkout — periksa kembali</h2><p className="mt-1 text-sm text-slate-500">Bandingkan kondisi kendaraan saat dikembalikan dengan checklist ketika mobil diambil.</p><div className="mt-4 space-y-3">{form.data.items.map((item, index) => <div key={item.checklist_code} className="grid gap-2 border-b border-slate-100 pb-3 sm:grid-cols-[1fr_150px]"><div><b>{item.checklist_name}</b><input placeholder="Catatan (opsional)" value={item.notes} onChange={event => updateItem(index, 'notes', event.target.value)} className="mt-1 w-full rounded-lg border-slate-200 text-sm"/></div><select value={item.condition_status} onChange={event => updateItem(index, 'condition_status', event.target.value)} className="rounded-lg border-slate-200"><option value="GOOD">Baik</option><option value="DAMAGED">Rusak</option><option value="MISSING">Hilang</option></select></div>)}</div></div>}{[['damage_fee', 'Biaya kerusakan'], ['fuel_fee', 'Biaya bahan bakar'], ['cleaning_fee', 'Biaya kebersihan']].map(([key, label]) => <label key={key}>{label}<input type="number" min="0" value={form.data[key]} onChange={event => form.setData(key, event.target.value)} className="mt-1 w-full rounded-xl border-slate-200"/></label>)}<label className="sm:col-span-2">Catatan pemeriksaan<textarea value={form.data.notes} onChange={event => form.setData('notes', event.target.value)} className="mt-1 w-full rounded-xl border-slate-200"/></label><button disabled={form.processing} className="sm:col-span-2 rounded-xl bg-indigo-600 py-3 font-bold text-white disabled:opacity-50">Konfirmasi check-in</button></form></div></AuthenticatedLayout>;
}
