import { Head, router } from '@inertiajs/react';
import { useState } from 'react';
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';

export default function Index({ customers, search }) {
    const [query, setQuery] = useState(search || '');
    const submit = (event) => { event.preventDefault(); router.get(route('admin.customers.index'), { search: query || undefined }, { preserveState: true, replace: true }); };
    return <AuthenticatedLayout header="Pelanggan"><Head title="Pelanggan" /><div className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-2xl font-black">Daftar pelanggan</h1><p className="mt-1 text-slate-500">Data kontak dan jumlah booking pelanggan.</p></div><form onSubmit={submit} className="flex gap-2"><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Cari nama, email, telepon" className="rounded-xl border-slate-200" /><button className="rounded-xl bg-indigo-600 px-4 py-2 font-semibold text-white">Cari</button></form></div><div className="mt-7 overflow-hidden rounded-2xl bg-white shadow-sm ring-1 ring-slate-200"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-6 py-4">Pelanggan</th><th className="px-6 py-4">Kontak</th><th className="px-6 py-4">Akun</th><th className="px-6 py-4 text-center">Booking</th><th className="px-6 py-4">Status</th></tr></thead><tbody>{customers.data.length ? customers.data.map(customer => <tr key={customer.id} className="border-t border-slate-100"><td className="px-6 py-4"><b>{customer.full_name}</b><p className="mt-1 text-xs text-slate-500">{customer.customer_code}</p></td><td className="px-6 py-4">{customer.phone}<p className="mt-1 text-slate-500">{customer.email || '—'}</p></td><td className="px-6 py-4"><span className={`rounded-full px-3 py-1 text-xs font-bold ${customer.user_id ? 'bg-emerald-50 text-emerald-700' : 'bg-slate-100 text-slate-600'}`}>{customer.user_id ? 'Login' : 'Tamu'}</span></td><td className="px-6 py-4 text-center font-bold">{customer.bookings_count}</td><td className="px-6 py-4"><span className="rounded-full bg-blue-50 px-3 py-1 text-xs font-bold text-blue-700">{customer.status}</span></td></tr>) : <tr><td colSpan="5" className="px-6 py-12 text-center text-slate-500">Belum ada data pelanggan.</td></tr>}</tbody></table></div></AuthenticatedLayout>;
}
