<?php
namespace App\Enums;
enum BookingStatus: string { case DRAFT='DRAFT'; case WAITING_PAYMENT='WAITING_PAYMENT'; case PAID='PAID'; case CONFIRMED='CONFIRMED'; case READY_FOR_PICKUP='READY_FOR_PICKUP'; case IN_USE='IN_USE'; case RETURN_INSPECTION='RETURN_INSPECTION'; case COMPLETED='COMPLETED'; case CANCELLED='CANCELLED'; case EXPIRED='EXPIRED'; case REFUNDED='REFUNDED'; }
